// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAcd7r50nZNDa_wsvNN_Zo7QVABf1_BJLo',
    appId: '1:1092723928362:web:e9544e25480f78c6d3c253',
    messagingSenderId: '1092723928362',
    projectId: 'notification-511a7',
    authDomain: 'notification-511a7.firebaseapp.com',
    storageBucket: 'notification-511a7.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBn9Hf8brz6Dt2jaf6MP4vLJKlOlsRX_gw',
    appId: '1:1092723928362:android:c9b0ba407fe62a18d3c253',
    messagingSenderId: '1092723928362',
    projectId: 'notification-511a7',
    storageBucket: 'notification-511a7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBqaj_gLyAN8kjefJVEg6LeMGHmWrWVjUA',
    appId: '1:1092723928362:ios:4ce34eac871cee78d3c253',
    messagingSenderId: '1092723928362',
    projectId: 'notification-511a7',
    storageBucket: 'notification-511a7.appspot.com',
    iosBundleId: 'com.example.medcare3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBqaj_gLyAN8kjefJVEg6LeMGHmWrWVjUA',
    appId: '1:1092723928362:ios:446c5e55a0b5f5fed3c253',
    messagingSenderId: '1092723928362',
    projectId: 'notification-511a7',
    storageBucket: 'notification-511a7.appspot.com',
    iosBundleId: 'com.example.medcare3.RunnerTests',
  );
}
